spring:
   datasource:
      username: climbing
      password: climbing
      url: jdbc:mysql://localhost:3306/climbing
  
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      
   sql: 
      init:
         mode: never 